# Generated by Django 3.2.6 on 2021-08-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0003_rename_brand_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='BrandId',
        ),
    ]
