# Generated by Django 3.2.6 on 2021-08-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0004_remove_brands_brandid'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='BrandId',
            field=models.IntegerField(default=None),
        ),
    ]
