# Generated by Django 3.2.6 on 2021-08-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0006_alter_brands_brandid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='BrandId',
        ),
    ]
