# Generated by Django 3.2.6 on 2021-08-10 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0001_initial'),
        ('Media', '0002_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('TelephoneNO', models.CharField(max_length=255)),
                ('DateOfBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_media_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_model')),
                ('mediaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Media.media_model')),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.store_model')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Instrument_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_model')),
                ('musical_instrumentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.store_musical_instrument')),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.store_model')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankID', models.IntegerField()),
                ('bank_Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Sortcode', models.IntegerField()),
                ('AccountNO', models.IntegerField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer_model')),
            ],
        ),
    ]
