# Generated by Django 3.2.6 on 2021-08-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_model',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
