# Generated by Django 3.2.6 on 2021-08-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_customer_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
