# Generated by Django 3.2.6 on 2021-08-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Media_type', models.IntegerField(default=False)),
                ('Media_name', models.CharField(max_length=255)),
                ('Media_description', models.CharField(max_length=255)),
            ],
        ),
    ]
