# Generated by Django 3.2.6 on 2021-08-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeID', models.IntegerField()),
                ('mediaID', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Store_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_phone', models.CharField(max_length=255)),
                ('store_email', models.CharField(max_length=255)),
                ('store_map', models.CharField(max_length=255)),
                ('store_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Store_musical_instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeID', models.IntegerField()),
                ('musical_instrumentId', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
