# Generated by Django 3.2.6 on 2021-08-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse_instrument',
            fields=[
                ('Warehouse_instrumentCode', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('musical_instrumentId', models.IntegerField(default=0)),
                ('Stock', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Warehouse_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Warehouse_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Warehouse_maps',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Warehouse_phone',
            field=models.CharField(max_length=255),
        ),
    ]
