# Generated by Django 3.2.6 on 2021-08-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0002_auto_20210807_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse_instrument',
            name='Warehouse_instrumentCode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
