# Generated by Django 3.2.6 on 2021-08-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0004_warehouse_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse_instrument',
            old_name='Warehouse_instrumentCode',
            new_name='Warehouse_Code',
        ),
        migrations.RemoveField(
            model_name='warehouse_media',
            name='warehouse_code',
        ),
    ]
