# Generated by Django 3.2.6 on 2021-08-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0005_auto_20210807_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse_instrument',
            old_name='cost',
            new_name='Cost',
        ),
        migrations.RenameField(
            model_name='warehouse_instrument',
            old_name='Warehouse_Code',
            new_name='Warehouse_code',
        ),
        migrations.RenameField(
            model_name='warehouse_instrument',
            old_name='Stock',
            new_name='stock',
        ),
    ]
