# Generated by Django 3.2.6 on 2021-08-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0006_auto_20210807_0624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warehouse_instrument',
            new_name='Warehouse_instruments',
        ),
        migrations.RenameField(
            model_name='warehouse_instruments',
            old_name='musical_instrumentId',
            new_name='musical_instrumentid',
        ),
    ]
