# Generated by Django 3.2.6 on 2021-08-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0007_auto_20210807_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse_instrument',
            fields=[
                ('Warehouse_code', models.IntegerField(primary_key=True, serialize=False)),
                ('musical_instrumentid', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('Cost', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Warehouse_instruments',
        ),
    ]
