# Generated by Django 3.2.6 on 2021-08-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0008_auto_20210807_0633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse_instrument',
        ),
    ]
