# Generated by Django 3.2.6 on 2021-08-06 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0007_remove_brands_brandid'),
        ('Music_Instrument', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instruments_Name', models.CharField(blank=True, default='', max_length=255)),
                ('Instruments_Description', models.CharField(blank=True, default='', max_length=255)),
                ('Instruments_BrandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brand.brands')),
            ],
        ),
    ]
