# Generated by Django 3.2.6 on 2021-08-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music_Instrument', '0002_instrument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='Instruments_Description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='Instruments_Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instrument_type',
            name='Instruments_Description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instrument_type',
            name='Instruments_Name',
            field=models.CharField(max_length=255),
        ),
    ]
